In [2]:
import pandas as pd
import yfinance as yf
import numpy as np

In [3]:
# Récupérer la liste des entreprises du S&P 500 depuis Wikipedia
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
df_sp500 = pd.read_html(url)[0]

# Afficher les premières lignes
df_sp500.head()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [4]:
#Je récupère la market cap avec cette fonction
def get_market_cap(symbol):
    try:
        stock = yf.Ticker(symbol)
        market_cap = stock.info['marketCap']
        return market_cap
    except KeyError:
        return None

In [5]:
#Je crée une nouvelle colonne en appliquant ma fonction pour chaque valeur de la colonne Symbol
df_sp500['MarketCap'] = df_sp500['Symbol'].apply(get_market_cap)

In [6]:
#J'utilise .isna() avec .any(axis = 1) qui permet de voir s'il y au moins (.any()) un NaN par ligne (axis = 1)
lignes_market_cap_na = df_sp500[df_sp500.isna().any(axis = 1)]
lignes_market_cap_na

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,MarketCap
60,BRK.B,Berkshire Hathaway,Financials,Multi-Sector Holdings,"Omaha, Nebraska",2010-02-16,1067983,1839,NaN
75,BF.B,Brown–Forman,Consumer Staples,Distillers & Vintners,"Louisville, Kentucky",1982-10-31,14693,1870,NaN

In [7]:
#En consultant Yahoo Finance, je récupère les ticker des entreprises correspondantes pour trouver leur marketCap avec yfinance

df_sp500.loc[60, 'Symbol'] = 'BRK-B'
df_sp500.loc[75, 'Symbol'] = 'BF-B'

df_sp500.loc[60, 'MarketCap'] = yf.Ticker('BRK-B').info['marketCap']
df_sp500.loc[75, 'MarketCap'] = yf.Ticker('BF-B').info['marketCap']

In [8]:
df_sp500_MC = df_sp500.sort_values(by = 'MarketCap', ascending = False)

In [9]:
df_sp500_MC

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,MarketCap
39,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977,3.508515e+12
349,NVDA,Nvidia,Information Technology,Semiconductors,"Santa Clara, California",2001-11-30,1045810,1993,3.444257e+12
319,MSFT,Microsoft,Information Technology,Systems Software,"Redmond, Washington",1994-06-01,789019,1975,3.157035e+12
20,GOOG,Alphabet Inc. (Class C),Communication Services,Interactive Media & Services,"Mountain View, California",2006-04-03,1652044,1998,2.013321e+12
19,GOOGL,Alphabet Inc. (Class A),Communication Services,Interactive Media & Services,"Mountain View, California",2014-04-03,1652044,1998,2.013318e+12
...,...,...,...,...,...,...,...,...,...
258,IVZ,Invesco,Financials,Asset Management & Custody Banks,"Atlanta, Georgia",2008-08-21,914208,1935,7.918428e+09
199,FMC,FMC Corporation,Materials,Fertilizers & Agricultural Chemicals,"Philadelphia, Pennsylvania",2009-08-19,37785,1883,7.676676e+09
69,BWA,BorgWarner,Consumer Discretionary,Automotive Parts & Equipment,"Auburn Hills, Michigan",2011-12-19,908255,1880,7.618873e+09
364,PARA,Paramount Global,Communication Services,Movies & Entertainment,"New York City, New York",1994-09-30,813828,2019 (Paramount Pictures 1912),7.340686e+09
24,AMTM,Amentum,Industrials,Diversified Support Services,"Chantilly, Virginia",2024-09-30,2011286,2020,7.291761e+09

In [10]:
#df_sp500_MC.to_csv('C:/Users/gabri/OneDrive/Bureau/PiCarréTrading/snp_500.csv', index=False)